export { PageLayout } from './page/page.layout'
export { Flex } from './flex/flex.component'
export { SideBar } from './sidebar/sidebar.layout'
export { Content } from './content/content.layout'
export { SideBarMenu } from './sidebar-menu/sidebar-menu.layout'
export { ScrollBox } from './scrollbox/scrollbox.layout'
export { Header } from './header/header.layout'
export { Chat } from './chat/chat.layout'
export { VideoPlayer } from './video-player/video-player.layout'
export { ChatField } from './chat-field/chat-field.layout'
export { ChatTabs } from './chat-tabs/chat-tabs.layout'
export { Form } from './form/form.layout'

export { ModalWindow } from './modal-window/modal-window.layout'
export { ConfirmModalWindow } from './modals/confirm-modal/confirm-modal.layout'
export { AttachModalWindow } from './modals/attach-modal/attach-modal.layout'

export { LoginForm } from './login-form/login-form.layout'
export { SignUpForm } from './signup-form/signup-form.layout'
